### ISSUE TITLE
Area, Area% Filter fail to operate

### ISSUE THREAD

**Issue by eselmeister** [eclipse-chemclipse/chemclipse#802]
The settings seem to be parsed incorrectly.

**Comment by eselmeister** [comment]
```
!ENTRY org.eclipse.ui 4 0 2021-10-29 06:11:00.944
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.IllegalArgumentException: No enum constant org.eclipse.chemclipse.xxd.model.support.TreatmentOption.Deactivate peak
	at java.lang.Enum.valueOf(Enum.java:238)
	at org.eclipse.chemclipse.ux.extension.xxd.ui.methods.WidgetItem.createLabeledEnumComboViewerWidget(WidgetItem.java:428)
	at org.eclipse.chemclipse.ux.extension.xxd.ui.methods.WidgetItem.createControl(WidgetItem.java:232)
	at org.eclipse.chemclipse.ux.extension.xxd.ui.methods.WidgetItem.initializeControl(WidgetItem.java:85)
	at org.eclipse.chemclipse.ux.extension.xxd.ui.methods.SettingsUI$SettingsUIControlImplementation.createOptionWidgets(SettingsUI.java:149)
	at org.eclipse.chemclipse.ux.extension.xxd.ui.methods.SettingsUI$SettingsUIControlImplementation.<init>(SettingsUI.java:120)
	at org.eclipse.chemclipse.ux.extension.xxd.ui.methods.SettingsUI$DefaultSettingsUIProvider.createUI(SettingsUI.java:94)
	at org.eclipse.chemclipse.ux.extension.xxd.ui.methods.SettingsUI.<init>(SettingsUI.java:50)
	at org.eclipse.chemclipse.ux.extension.xxd.ui.methods.SettingsPreferencesPage.createSettingsUI(SettingsPreferencesPage.java:149)
	at org.eclipse.chemclipse.ux.extension.xxd.ui.methods.SettingsPreferencesPage.createUserOptions(SettingsPreferencesPage.java:133)
	at org.eclipse.chemclipse.ux.extension.xxd.ui.methods.SettingsPreferencesPage.createOptionSection(SettingsPreferencesPage.java:97)
	at org.eclipse.chemclipse.ux.extension.xxd.ui.methods.SettingsPreferencesPage.createControl(SettingsPreferencesPage.java:64)
	at org.eclipse.jface.wizard.Wizard.createPageControls(Wizard.java:176)
	at org.eclipse.jface.wizard.WizardDialog.createPageControls(WizardDialog.java:682)
	at org.eclipse.jface.wizard.WizardDialog.createContents(WizardDialog.java:574)
	at org.eclipse.jface.window.Window.create(Window.java:426)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1096)
	at org.eclipse.jface.window.Window.open(Window.java:783)
	at org.eclipse.chemclipse.ux.extension.xxd.ui.methods.SettingsWizard.openEditPreferencesWizard(SettingsWizard.java:74)
	at org.eclipse.chemclipse.ux.extension.xxd.ui.methods.SettingsWizard.getSettings(SettingsWizard.java:143)
	at org.eclipse.chemclipse.ux.extension.xxd.ui.swt.editors.ExtendedChromatogramUI.executeSupplier(ExtendedChromatogramUI.java:536)
	at org.eclipse.chemclipse.ux.extension.xxd.ui.swt.editors.ProcessorSupplierMenuEntry.execute(ProcessorSupplierMenuEntry.java:63)
	at org.eclipse.swtchart.extensions.core.ScrollableChart$6.widgetSelected(ScrollableChart.java:1653)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5686)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1370)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4940)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4518)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1170)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1059)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:667)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:597)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.chemclipse.rcp.app.ui.internal.support.ApplicationSupportDefault.start(ApplicationSupportDefault.java:26)
	at org.eclipse.chemclipse.rcp.app.ui.Application.start(Application.java:61)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:656)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:592)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1498)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1471)
```

**Comment by eselmeister** [comment]
![Bildschirmfoto von 2021-10-29 11-46-12](https://user-images.githubusercontent.com/686671/139414110-5aedd9ae-6fb8-4676-bd4f-2edbb310a6db.png)

![Bildschirmfoto von 2021-10-29 11-46-17](https://user-images.githubusercontent.com/686671/139414128-a7729eb2-dd82-4af3-a51e-e2e7f62c9f4b.png)
