### ISSUE TITLE
Unhandled event loop exception in Retention Index Calculator

### ISSUE THREAD

**Issue by Mailaender** [eclipse-chemclipse/chemclipse#803]
> ERROR	Retention Index Calculator	The retention index map could not be found. Is a calibration (*.cal) file or chromatogram RI map available?

**Comment by Mailaender** [comment]
```
java.lang.NullPointerException
	at org.eclipse.chemclipse.processing.ui.support.ProcessingInfoPartSupport.logErrorMessage(ProcessingInfoPartSupport.java:190)
	at org.eclipse.chemclipse.processing.ui.support.ProcessingInfoPartSupport.update(ProcessingInfoPartSupport.java:76)
	at org.eclipse.chemclipse.ux.extension.xxd.ui.swt.editors.ExtendedChromatogramUI$2.run(ExtendedChromatogramUI.java:576)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4915)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4521)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.block(ModalContext.java:165)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:369)
	at org.eclipse.jface.dialogs.ProgressMonitorDialog.run(ProgressMonitorDialog.java:471)
	at org.eclipse.chemclipse.ux.extension.xxd.ui.swt.editors.ExtendedChromatogramUI.processChromatogram(ExtendedChromatogramUI.java:480)
	at org.eclipse.chemclipse.ux.extension.xxd.ui.swt.editors.ExtendedChromatogramUI.executeSupplier(ExtendedChromatogramUI.java:548)
	at org.eclipse.chemclipse.ux.extension.xxd.ui.swt.editors.ProcessorSupplierMenuEntry.execute(ProcessorSupplierMenuEntry.java:63)
	at org.eclipse.swtchart.extensions.core.ScrollableChart$6.widgetSelected(ScrollableChart.java:1653)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5686)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1370)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4940)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4518)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1170)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1059)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:667)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:597)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.chemclipse.rcp.app.ui.internal.support.ApplicationSupportDefault.start(ApplicationSupportDefault.java:26)
	at org.eclipse.chemclipse.rcp.app.ui.Application.start(Application.java:61)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:656)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:592)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1498)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1471)
```

**Comment by Mailaender** [comment]
Reproduce with

![image](https://user-images.githubusercontent.com/756669/139847412-88fdf8c8-daa0-4041-b314-37a91e62874a.png)

First derivative peak detection and

![image](https://user-images.githubusercontent.com/756669/139847537-a62d53fd-c773-46c0-b220-c7b7afff0f55.png)

**Comment by Mailaender** [comment]
In the .CAL file there has to be

```
#COLUMN_NAME=DEFAULT
```

which makes this a regression from https://github.com/eclipse/chemclipse/pull/774/commits/fec69daef344a3f256d3da9e3ffa224526b1d2f3.

**Comment by eselmeister** [comment]
Ah yes, that's the reason why it fails. Let me review it and try to find a solution.
